# ===== STAGE 1: build =====
FROM node:20.19-slim AS builder

WORKDIR /app

ARG NEXT_PUBLIC_FACEBOOK
ARG NEXT_PUBLIC_INSTAGRAM
ARG NEXT_PUBLIC_LINKEDIN
ARG NEXT_PUBLIC_WHATSAPP
ARG NEXT_PUBLIC_EMAIL

ENV NEXT_PUBLIC_FACEBOOK=$NEXT_PUBLIC_FACEBOOK
ENV NEXT_PUBLIC_INSTAGRAM=$NEXT_PUBLIC_INSTAGRAM
ENV NEXT_PUBLIC_LINKEDIN=$NEXT_PUBLIC_LINKEDIN
ENV NEXT_PUBLIC_WHATSAPP=$NEXT_PUBLIC_WHATSAPP
ENV NEXT_PUBLIC_EMAIL=$NEXT_PUBLIC_EMAIL

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build


# ===== STAGE 2: arquivos estáticos =====
FROM nginx:1.27-alpine

COPY docker/static.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/out /usr/share/nginx/html

EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]
