services:
  web:
    container_name: ampla-landing
    image: ampla-tec-landing
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_FACEBOOK: ${NEXT_PUBLIC_FACEBOOK}
        NEXT_PUBLIC_INSTAGRAM: ${NEXT_PUBLIC_INSTAGRAM}
        NEXT_PUBLIC_LINKEDIN: ${NEXT_PUBLIC_LINKEDIN}
        NEXT_PUBLIC_WHATSAPP: ${NEXT_PUBLIC_WHATSAPP}
        NEXT_PUBLIC_EMAIL: ${NEXT_PUBLIC_EMAIL}
      env_file:
        - .env
    environment:
      NEXT_PUBLIC_FACEBOOK: ${NEXT_PUBLIC_FACEBOOK}
      NEXT_PUBLIC_INSTAGRAM: ${NEXT_PUBLIC_INSTAGRAM}
      NEXT_PUBLIC_LINKEDIN: ${NEXT_PUBLIC_LINKEDIN}
      NEXT_PUBLIC_WHATSAPP: ${NEXT_PUBLIC_WHATSAPP}
      NEXT_PUBLIC_EMAIL: ${NEXT_PUBLIC_EMAIL}
      NODE_ENV: production
    expose:
      - "3000"
    restart: unless-stopped
    networks:
      - webnet

  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - web
    restart: unless-stopped
    networks:
      - webnet

networks:
  webnet:
    driver: bridge